name = IO-Path-AutoDecompress

[ReadmeFromPod]
; enabled = false
filename = doc/IO-Path-AutoDecompress.rakudoc

[UploadToZef]

[PruneFiles]
; match = ^ 'xt/'

[Badges]
provider = github-actions/linux.yml
provider = github-actions/macos.yml
provider = github-actions/windows.yml
